models_params:
    Classification:
        LogisticRegression:
            C:
                - 0.01
                - 0.1
                - 1.0
    Regression:
        ElasticNet:
            alpha:
                - 0.1
                - 0.01
                - 1.0
            l1_ratio:
              - 0.5
              - 0.05
              - 1.0
        GradientBoostingRegressor:
            n_estimators:
                - 100
                - 150
                - 200
            learning_rate:
                - 0.01
                - 0.1
                - 0.5
            max_depth:
                - 3
                - 5
    cv_folds: 5



pipeline_input:
    classification_target: c_target
    regression_target: r_target
    forecast_variable: forcast_this

    classification_features:
        - feat1
        - feat2


    regression_features:
        - feat1
        - feat2
        - feat3
